// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
 
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
 
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZutU4_iIWikvnH0E65cFrExaATEW9PKo',
    appId: '1:1036394851746:web:33ede35e3de684ec7196fb',
    messagingSenderId: '1036394851746',
    projectId: 'tat367-333c6',
    authDomain: 'tat367-333c6.firebaseapp.com',
    storageBucket: 'tat367-333c6.firebasestorage.app',
    measurementId: 'G-6W2JFDEJQW',
  );
 
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoTjiabcYwLpGc3lzuhtbDnL7OmhKW14E',
    appId: '1:1036394851746:android:f6f8ffe3fd6d37557196fb',
    messagingSenderId: '1036394851746',
    projectId: 'tat367-333c6',
    storageBucket: 'tat367-333c6.firebasestorage.app',
  );
 
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKKI_n3HT8qKUiIA3g90Y4gHOT6OPOWg8',
    appId: '1:1036394851746:ios:1366be3516c780977196fb',
    messagingSenderId: '1036394851746',
    projectId: 'tat367-333c6',
    storageBucket: 'tat367-333c6.firebasestorage.app',
    iosBundleId: 'com.example.tat367',
  );
 
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKKI_n3HT8qKUiIA3g90Y4gHOT6OPOWg8',
    appId: '1:1036394851746:ios:1366be3516c780977196fb',
    messagingSenderId: '1036394851746',
    projectId: 'tat367-333c6',
    storageBucket: 'tat367-333c6.firebasestorage.app',
    iosBundleId: 'com.example.tat367',
  );
 
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZutU4_iIWikvnH0E65cFrExaATEW9PKo',
    appId: '1:1036394851746:web:1bde785174efb41b7196fb',
    messagingSenderId: '1036394851746',
    projectId: 'tat367-333c6',
    authDomain: 'tat367-333c6.firebaseapp.com',
    storageBucket: 'tat367-333c6.firebasestorage.app',
    measurementId: 'G-H1B5NY3DRN',
  );
}